// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace PlateformeEvaluation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215000920_AddUserIdToCandidatModel")]
    partial class AddUserIdToCandidatModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Candidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidats");
                });

            modelBuilder.Entity("WebApplication1.Models.Candidature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCandidature")
                        .HasColumnType("datetime2");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("WebApplication1.Models.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Evaluations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Test d'intelligence basé sur le raisonnement logique, la résolution de problèmes et les compétences relationnelles",
                            DureeMinutes = 30,
                            Titre = "Évaluation Intelligences Logiques et Relationnelles"
                        },
                        new
                        {
                            Id = 2,
                            DateCreation = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Test de compréhension française",
                            DureeMinutes = 20,
                            Titre = "Évaluation Français"
                        },
                        new
                        {
                            Id = 3,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Business communication vocabulary and situational understanding",
                            DureeMinutes = 20,
                            Titre = "English - Corporate Communication Test"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.OptionReponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstCorrecte")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("OptionsReponse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstCorrecte = false,
                            QuestionId = 1,
                            Texte = "0 fois"
                        },
                        new
                        {
                            Id = 2,
                            EstCorrecte = true,
                            QuestionId = 1,
                            Texte = "1 fois"
                        },
                        new
                        {
                            Id = 3,
                            EstCorrecte = false,
                            QuestionId = 1,
                            Texte = "2 fois"
                        },
                        new
                        {
                            Id = 4,
                            EstCorrecte = false,
                            QuestionId = 1,
                            Texte = "Impossible à déterminer"
                        },
                        new
                        {
                            Id = 5,
                            EstCorrecte = false,
                            QuestionId = 2,
                            Texte = "24"
                        },
                        new
                        {
                            Id = 6,
                            EstCorrecte = true,
                            QuestionId = 2,
                            Texte = "32"
                        },
                        new
                        {
                            Id = 7,
                            EstCorrecte = false,
                            QuestionId = 2,
                            Texte = "30"
                        },
                        new
                        {
                            Id = 8,
                            EstCorrecte = false,
                            QuestionId = 2,
                            Texte = "36"
                        },
                        new
                        {
                            Id = 9,
                            EstCorrecte = false,
                            QuestionId = 3,
                            Texte = "0"
                        },
                        new
                        {
                            Id = 10,
                            EstCorrecte = true,
                            QuestionId = 3,
                            Texte = "1"
                        },
                        new
                        {
                            Id = 11,
                            EstCorrecte = false,
                            QuestionId = 3,
                            Texte = "3"
                        },
                        new
                        {
                            Id = 12,
                            EstCorrecte = false,
                            QuestionId = 3,
                            Texte = "2"
                        },
                        new
                        {
                            Id = 13,
                            EstCorrecte = false,
                            QuestionId = 4,
                            Texte = "8 équipes"
                        },
                        new
                        {
                            Id = 14,
                            EstCorrecte = true,
                            QuestionId = 4,
                            Texte = "9 équipes"
                        },
                        new
                        {
                            Id = 15,
                            EstCorrecte = false,
                            QuestionId = 4,
                            Texte = "10 équipes"
                        },
                        new
                        {
                            Id = 16,
                            EstCorrecte = false,
                            QuestionId = 4,
                            Texte = "7 équipes"
                        },
                        new
                        {
                            Id = 17,
                            EstCorrecte = false,
                            QuestionId = 5,
                            Texte = "A - Refuser directement"
                        },
                        new
                        {
                            Id = 18,
                            EstCorrecte = false,
                            QuestionId = 5,
                            Texte = "B - Accepter sans question"
                        },
                        new
                        {
                            Id = 19,
                            EstCorrecte = true,
                            QuestionId = 5,
                            Texte = "C - Proposer une alternative"
                        },
                        new
                        {
                            Id = 20,
                            EstCorrecte = false,
                            QuestionId = 5,
                            Texte = "Repousser le deadline"
                        },
                        new
                        {
                            Id = 21,
                            EstCorrecte = false,
                            QuestionId = 6,
                            Texte = "E"
                        },
                        new
                        {
                            Id = 22,
                            EstCorrecte = true,
                            QuestionId = 6,
                            Texte = "J"
                        },
                        new
                        {
                            Id = 23,
                            EstCorrecte = false,
                            QuestionId = 6,
                            Texte = "A"
                        },
                        new
                        {
                            Id = 24,
                            EstCorrecte = false,
                            QuestionId = 6,
                            Texte = "F"
                        },
                        new
                        {
                            Id = 25,
                            EstCorrecte = false,
                            QuestionId = 7,
                            Texte = "L'ignorer et espérer que personne ne la trouve"
                        },
                        new
                        {
                            Id = 26,
                            EstCorrecte = true,
                            QuestionId = 7,
                            Texte = "En informer immédiatement le manager et proposer une solution"
                        },
                        new
                        {
                            Id = 27,
                            EstCorrecte = false,
                            QuestionId = 7,
                            Texte = "Chercher à blâmer quelqu'un d'autre"
                        },
                        new
                        {
                            Id = 28,
                            EstCorrecte = false,
                            QuestionId = 7,
                            Texte = "Attendre que quelqu'un d'autre la découvre"
                        },
                        new
                        {
                            Id = 29,
                            EstCorrecte = false,
                            QuestionId = 8,
                            Texte = "C'est une excellente métrique objective"
                        },
                        new
                        {
                            Id = 30,
                            EstCorrecte = false,
                            QuestionId = 8,
                            Texte = "Cela encourage la qualité plutôt que la quantité"
                        },
                        new
                        {
                            Id = 31,
                            EstCorrecte = true,
                            QuestionId = 8,
                            Texte = "Cela incite à écrire du code inutile et de mauvaise qualité"
                        },
                        new
                        {
                            Id = 32,
                            EstCorrecte = false,
                            QuestionId = 8,
                            Texte = "C'est la seule façon de mesurer la productivité"
                        },
                        new
                        {
                            Id = 33,
                            EstCorrecte = false,
                            QuestionId = 9,
                            Texte = "Toujours choisir A pour la rapidité"
                        },
                        new
                        {
                            Id = 34,
                            EstCorrecte = true,
                            QuestionId = 9,
                            Texte = "Analyser le coût total sur 5 ans (dev + maintenance) et choisir B si c'est inférieur"
                        },
                        new
                        {
                            Id = 35,
                            EstCorrecte = false,
                            QuestionId = 9,
                            Texte = "Choisir toujours la solution la plus complexe"
                        },
                        new
                        {
                            Id = 36,
                            EstCorrecte = false,
                            QuestionId = 9,
                            Texte = "C'est équivalent, le choix n'importe pas"
                        },
                        new
                        {
                            Id = 37,
                            EstCorrecte = false,
                            QuestionId = 10,
                            Texte = "Le blâmer publiquement pour l'humilier"
                        },
                        new
                        {
                            Id = 38,
                            EstCorrecte = true,
                            QuestionId = 10,
                            Texte = "En discuter en privé, comprendre son processus, lui proposer des solutions"
                        },
                        new
                        {
                            Id = 39,
                            EstCorrecte = false,
                            QuestionId = 10,
                            Texte = "Ignorer et laisser quelqu'un d'autre le corriger"
                        },
                        new
                        {
                            Id = 40,
                            EstCorrecte = false,
                            QuestionId = 10,
                            Texte = "Le reporter au manager immédiatement"
                        },
                        new
                        {
                            Id = 41,
                            EstCorrecte = true,
                            QuestionId = 11,
                            Texte = "21, 34"
                        },
                        new
                        {
                            Id = 42,
                            EstCorrecte = false,
                            QuestionId = 11,
                            Texte = "20, 33"
                        },
                        new
                        {
                            Id = 43,
                            EstCorrecte = false,
                            QuestionId = 11,
                            Texte = "15, 20"
                        },
                        new
                        {
                            Id = 44,
                            EstCorrecte = false,
                            QuestionId = 11,
                            Texte = "18, 31"
                        },
                        new
                        {
                            Id = 45,
                            EstCorrecte = false,
                            QuestionId = 12,
                            Texte = "Faire exactement ce qu'il demande sans question"
                        },
                        new
                        {
                            Id = 46,
                            EstCorrecte = false,
                            QuestionId = 12,
                            Texte = "Refuser catégoriquement"
                        },
                        new
                        {
                            Id = 47,
                            EstCorrecte = true,
                            QuestionId = 12,
                            Texte = "Documenter vos préoccupations, proposer des alternatives, puis laisser le client décider"
                        },
                        new
                        {
                            Id = 48,
                            EstCorrecte = false,
                            QuestionId = 12,
                            Texte = "Faire ce qu'il demande mais très lentement"
                        },
                        new
                        {
                            Id = 49,
                            EstCorrecte = false,
                            QuestionId = 13,
                            Texte = "A, car plus rapide"
                        },
                        new
                        {
                            Id = 50,
                            EstCorrecte = true,
                            QuestionId = 13,
                            Texte = "B ou C selon le contexte (durée du projet, maintenabilité future)"
                        },
                        new
                        {
                            Id = 51,
                            EstCorrecte = false,
                            QuestionId = 13,
                            Texte = "C toujours, peu importe le coût"
                        },
                        new
                        {
                            Id = 52,
                            EstCorrecte = false,
                            QuestionId = 13,
                            Texte = "Aucun, tous sont équivalents"
                        },
                        new
                        {
                            Id = 53,
                            EstCorrecte = false,
                            QuestionId = 14,
                            Texte = "A + B (9 ressources, 250€)"
                        },
                        new
                        {
                            Id = 54,
                            EstCorrecte = false,
                            QuestionId = 14,
                            Texte = "B + C (7 ressources, 230€)"
                        },
                        new
                        {
                            Id = 55,
                            EstCorrecte = true,
                            QuestionId = 14,
                            Texte = "A + C + allocations flexibles pour maximiser ROI"
                        },
                        new
                        {
                            Id = 56,
                            EstCorrecte = false,
                            QuestionId = 14,
                            Texte = "Tous les trois (impossible avec 10)"
                        },
                        new
                        {
                            Id = 57,
                            EstCorrecte = false,
                            QuestionId = 15,
                            Texte = "L'équipe n'est pas assez productive"
                        },
                        new
                        {
                            Id = 58,
                            EstCorrecte = true,
                            QuestionId = 15,
                            Texte = "Le projet est mal estimé, les attentes irréalistes, ou le processus est inefficace"
                        },
                        new
                        {
                            Id = 59,
                            EstCorrecte = false,
                            QuestionId = 15,
                            Texte = "Les développeurs sont paresseux"
                        },
                        new
                        {
                            Id = 60,
                            EstCorrecte = false,
                            QuestionId = 15,
                            Texte = "C'est normal dans l'industrie tech"
                        },
                        new
                        {
                            Id = 61,
                            EstCorrecte = false,
                            QuestionId = 16,
                            Texte = "Lancer le release avec le bug et prier"
                        },
                        new
                        {
                            Id = 62,
                            EstCorrecte = true,
                            QuestionId = 16,
                            Texte = "Évaluer l'impact, la probabilité d'occurrence, et décider si on retarde ou accepte le risque"
                        },
                        new
                        {
                            Id = 63,
                            EstCorrecte = false,
                            QuestionId = 16,
                            Texte = "Toujours corriger, peu importe le délai"
                        },
                        new
                        {
                            Id = 64,
                            EstCorrecte = false,
                            QuestionId = 16,
                            Texte = "Cacher le bug aux utilisateurs"
                        },
                        new
                        {
                            Id = 65,
                            EstCorrecte = false,
                            QuestionId = 17,
                            Texte = "Il est incompétent et doit être viré"
                        },
                        new
                        {
                            Id = 66,
                            EstCorrecte = true,
                            QuestionId = 17,
                            Texte = "Il ne lit pas la documentation ou ne la comprend pas"
                        },
                        new
                        {
                            Id = 67,
                            EstCorrecte = false,
                            QuestionId = 17,
                            Texte = "C'est normal pour tous les stagiaires"
                        },
                        new
                        {
                            Id = 68,
                            EstCorrecte = false,
                            QuestionId = 17,
                            Texte = "Il cherche de l'attention"
                        },
                        new
                        {
                            Id = 69,
                            EstCorrecte = false,
                            QuestionId = 18,
                            Texte = "Agile est toujours meilleur"
                        },
                        new
                        {
                            Id = 70,
                            EstCorrecte = true,
                            QuestionId = 18,
                            Texte = "Waterfall car requirements sont clairs et stables"
                        },
                        new
                        {
                            Id = 71,
                            EstCorrecte = false,
                            QuestionId = 18,
                            Texte = "Mélanger les deux"
                        },
                        new
                        {
                            Id = 72,
                            EstCorrecte = false,
                            QuestionId = 18,
                            Texte = "Waterfall est toujours meilleur"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EvaluationId = 1,
                            Points = 1,
                            Texte = "Si tous les vendredis soir je fais du sport, et aujourd'hui c'est samedi matin, combien de fois ai-je fait du sport cette semaine?",
                            Type = "logique_deduction"
                        },
                        new
                        {
                            Id = 2,
                            EvaluationId = 1,
                            Points = 1,
                            Texte = "Dans une suite numérique: 2, 4, 8, 16, ?, le prochain nombre est?",
                            Type = "reconnaissance_pattern"
                        },
                        new
                        {
                            Id = 3,
                            EvaluationId = 1,
                            Points = 1,
                            Texte = "Trois personnes entrent dans une salle. Deux en sortent. Combien de personnes restent dans la salle?",
                            Type = "logique_deduction"
                        },
                        new
                        {
                            Id = 4,
                            EvaluationId = 1,
                            Points = 2,
                            Texte = "Vous gérez une équipe de 5 personnes. Deux d'entre elles ne s'entendent pas. Elles refusent de travailler ensemble. Vous devez former une équipe de 3 personnes pour un projet. Quel est le nombre maximum d'équipes différentes que vous pouvez former?",
                            Type = "logique_combinatoire"
                        },
                        new
                        {
                            Id = 5,
                            EvaluationId = 1,
                            Points = 2,
                            Texte = "Un client demande une nouvelle fonctionnalité qui contredit le design actuel. Le deadline est dans 2 jours. Vous avez 3 options: (A) Refuser et expliquer pourquoi c'est mauvais, (B) Accepter sans discuter, (C) Proposer une alternative qui satisfait le besoin sans casser le design. Quelle est la meilleure approche managériale?",
                            Type = "soft_skills_decision"
                        },
                        new
                        {
                            Id = 6,
                            EvaluationId = 1,
                            Points = 2,
                            Texte = "Suite logique: J, F, M, A, M, J, J, A, S, O, N, D, ?",
                            Type = "reconnaissance_pattern"
                        },
                        new
                        {
                            Id = 7,
                            EvaluationId = 1,
                            Points = 2,
                            Texte = "Vous découvrez une erreur critique dans le code en production que vous avez écrit hier. L'équipe ne le sait pas encore. Que faites-vous?",
                            Type = "soft_skills_ethique"
                        },
                        new
                        {
                            Id = 8,
                            EvaluationId = 1,
                            Points = 3,
                            Texte = "Une entreprise mesure la performance des développeurs par le nombre de lignes de code écrites par jour. Qu'est-ce qui est problématique dans cette approche?",
                            Type = "thinking_critique"
                        },
                        new
                        {
                            Id = 9,
                            EvaluationId = 1,
                            Points = 3,
                            Texte = "Deux solutions techniques peuvent résoudre un problème: A (rapide à développer, coûteuse en maintenance) et B (plus lente à développer, peu coûteuse en maintenance). Le projet dure 5 ans. Quelle est la meilleure décision?",
                            Type = "strategic_thinking"
                        },
                        new
                        {
                            Id = 10,
                            EvaluationId = 1,
                            Points = 3,
                            Texte = "Un collègue junior fait une erreur qui cause un bug client. Comment gérez-vous cette situation pour favoriser l'apprentissage?",
                            Type = "leadership_soft_skills"
                        },
                        new
                        {
                            Id = 11,
                            EvaluationId = 1,
                            Points = 3,
                            Texte = "Pattern: 1, 1, 2, 3, 5, 8, 13, ?, ?",
                            Type = "reconnaissance_pattern_avancee"
                        },
                        new
                        {
                            Id = 12,
                            EvaluationId = 1,
                            Points = 3,
                            Texte = "Un client demande une feature que vous savez techniquement faisable mais nuisible pour l'UX. Vous l'expliquez mais il insiste. Quel est votre rôle?",
                            Type = "professional_advocacy"
                        },
                        new
                        {
                            Id = 13,
                            EvaluationId = 1,
                            Points = 3,
                            Texte = "Trois programmeurs codent le même module. Programmeur A finit en 2j (code complexe), Programmeur B finit en 4j (code lisible), Programmeur C finit en 5j (code brillant, maintenable). Quel est le meilleur pour l'entreprise à long terme?",
                            Type = "strategic_analysis"
                        },
                        new
                        {
                            Id = 14,
                            EvaluationId = 1,
                            Points = 3,
                            Texte = "Vous avez 10 ressources et 3 projets urgents. Le projet A rapporte 100€, B rapporte 150€, C rapporte 80€. A nécessite 5 ressources, B en 4, C en 3. Comment les allouez-vous?",
                            Type = "logique_optimisation"
                        },
                        new
                        {
                            Id = 15,
                            EvaluationId = 1,
                            Points = 3,
                            Texte = "Vous remarquez que votre équipe travaille constamment en overtime. Quel est le vrai problème selon vous?",
                            Type = "systemic_thinking"
                        },
                        new
                        {
                            Id = 16,
                            EvaluationId = 1,
                            Points = 3,
                            Texte = "Un bug critique est découvert juste avant le release. Il faut 3 jours pour le corriger. Quelle est la meilleure décision?",
                            Type = "strategic_decision_making"
                        },
                        new
                        {
                            Id = 17,
                            EvaluationId = 1,
                            Points = 3,
                            Texte = "Pattern comportemental: Un stagiaire pose toujours des questions basiques après avoir lu la doc. Que concluez-vous?",
                            Type = "pattern_recognition_behavior"
                        },
                        new
                        {
                            Id = 18,
                            EvaluationId = 1,
                            Points = 3,
                            Texte = "Deux approches: Agile (flexible, itérative) vs Waterfall (planning rigoureux). Pour un projet gouvernemental avec budget fixe et requirements clairs, quelle est la meilleure?",
                            Type = "contextual_methodology"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.ReponseCandidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OptionReponseId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("ReponseTexte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TentativeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OptionReponseId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TentativeId");

                    b.ToTable("ReponsesCandidats");
                });

            modelBuilder.Entity("WebApplication1.Models.Tentative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePassage")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.HasIndex("EvaluationId");

                    b.ToTable("Tentatives");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.Candidature", b =>
                {
                    b.HasOne("WebApplication1.Models.Candidat", "Candidat")
                        .WithMany("Candidatures")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");
                });

            modelBuilder.Entity("WebApplication1.Models.OptionReponse", b =>
                {
                    b.HasOne("WebApplication1.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("WebApplication1.Models.Question", b =>
                {
                    b.HasOne("WebApplication1.Models.Evaluation", "Evaluation")
                        .WithMany("Questions")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("WebApplication1.Models.ReponseCandidat", b =>
                {
                    b.HasOne("WebApplication1.Models.OptionReponse", "OptionReponse")
                        .WithMany("ReponsesCandidats")
                        .HasForeignKey("OptionReponseId");

                    b.HasOne("WebApplication1.Models.Question", "Question")
                        .WithMany("ReponsesCandidats")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Tentative", "Tentative")
                        .WithMany("ReponsesCandidats")
                        .HasForeignKey("TentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionReponse");

                    b.Navigation("Question");

                    b.Navigation("Tentative");
                });

            modelBuilder.Entity("WebApplication1.Models.Tentative", b =>
                {
                    b.HasOne("WebApplication1.Models.Candidat", "Candidat")
                        .WithMany("Tentatives")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Evaluation", "Evaluation")
                        .WithMany("Tentatives")
                        .HasForeignKey("EvaluationId");

                    b.Navigation("Candidat");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("WebApplication1.Models.Candidat", b =>
                {
                    b.Navigation("Candidatures");

                    b.Navigation("Tentatives");
                });

            modelBuilder.Entity("WebApplication1.Models.Evaluation", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Tentatives");
                });

            modelBuilder.Entity("WebApplication1.Models.OptionReponse", b =>
                {
                    b.Navigation("ReponsesCandidats");
                });

            modelBuilder.Entity("WebApplication1.Models.Question", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("ReponsesCandidats");
                });

            modelBuilder.Entity("WebApplication1.Models.Tentative", b =>
                {
                    b.Navigation("ReponsesCandidats");
                });
#pragma warning restore 612, 618
        }
    }
}
